/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.grouptest_for_git;

import com.mycompany.theme.UIConstants;
import com.mycompany.components.MyLabel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author KoukChay
 */
public class UiTest extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UiTest.class.getName());

    /**
     * Creates new form UiTest
     */
    public UiTest() {
        initComponents();
        myTextField2.addPlaceholder("Enter Your Name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myComboBox1 = new com.mycompany.components.MyComboBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myTextField2 = new com.mycompany.components.MyTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myLabel1 = new com.mycompany.components.MyLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        myButton6 = new com.mycompany.components.MyButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton4 = new com.mycompany.components.MyButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton2 = new com.mycompany.components.MyButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton3 = new com.mycompany.components.MyButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton1 = new com.mycompany.components.MyButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton5 = new com.mycompany.components.MyButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        myButton7 = new com.mycompany.components.MyButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        sliderBtn = new com.mycompany.components.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setAlignmentY(1.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        myComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose", "Bold", "Normal", "Red" }));
        myComboBox1.setToolTipText("Choose");
        myComboBox1.addActionListener(this::myComboBox1ActionPerformed);
        jPanel1.add(myComboBox1);
        jPanel1.add(filler2);

        myTextField2.setAlignmentX(0.5F);
        myTextField2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        myTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTextField2MouseClicked(evt);
            }
        });
        jPanel1.add(myTextField2);
        jPanel1.add(filler3);
        jPanel1.add(filler4);

        myLabel1.setForeground(new java.awt.Color(204, 204, 255));
        myLabel1.setText("Your Name Will Show Here");
        myLabel1.setAlignmentX(0.5F);
        myLabel1.setPreferredSize(new java.awt.Dimension(180, 15));
        jPanel1.add(myLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setFocusCycleRoot(true);
        jPanel3.setMaximumSize(new java.awt.Dimension(125, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler5);

        myButton6.setText("myButton6");
        myButton6.setAlignmentX(0.5F);
        jPanel4.add(myButton6);
        jPanel4.add(filler8);

        myButton4.setText("myButton4");
        myButton4.setAlignmentX(0.5F);
        jPanel4.add(myButton4);
        jPanel4.add(filler9);

        myButton2.setText("myButton2");
        myButton2.setAlignmentX(0.5F);
        jPanel4.add(myButton2);
        jPanel4.add(filler10);

        myButton3.setText("Show Name");
        myButton3.setAlignmentX(0.5F);
        myButton3.setAlignmentY(CENTER_ALIGNMENT);
        myButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton3.setRolloverEnabled(false);
        myButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        myButton3.addActionListener(this::myButton3ActionPerformed);
        jPanel4.add(myButton3);
        jPanel4.add(filler7);

        myButton1.setText("nothing");
        myButton1.setAlignmentX(0.5F);
        jPanel4.add(myButton1);
        jPanel4.add(filler11);

        myButton5.setText("myButton5");
        myButton5.setAlignmentX(0.5F);
        jPanel4.add(myButton5);
        jPanel4.add(filler12);

        myButton7.setText("myButton7");
        myButton7.setAlignmentX(0.5F);
        jPanel4.add(myButton7);
        jPanel4.add(filler6);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 330));

        sliderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ui/images/Slider_2.png"))); // NOI18N
        sliderBtn.setRolloverEnabled(false);
        sliderBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ui/images/Slider_3.png"))); // NOI18N
        sliderBtn.addActionListener(this::sliderBtnActionPerformed);
        jPanel3.add(sliderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
        sliderBtn.setBackground(new java.awt.Color(0,0,0,0));
        sliderBtn.setOpaque(false);
        sliderBtn.setAlignmentY(LEFT_ALIGNMENT);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTextField2MouseClicked
        

        myLabel1.setText("Your Name will Show Here");
    }//GEN-LAST:event_myTextField2MouseClicked

    private void myComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myComboBox1ActionPerformed
        
    }//GEN-LAST:event_myComboBox1ActionPerformed

    private void sliderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliderBtnActionPerformed
        
        toggleSidebar();
    }//GEN-LAST:event_sliderBtnActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        String name = myTextField2.getText();
        System.out.println(name.trim().toLowerCase());
        if (name.trim().toLowerCase().equals("enter your name") || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Your Name First", "Name can't be Empty", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (myComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Choose your Font Style First", "select DropBox", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        myLabel1.setForeground(UIConstants.TEXT_COLOR);
        if (myComboBox1.getSelectedItem().equals("Bold")) {

            myLabel1.setFont(new Font("Fira Code", Font.BOLD, 16));

        } else if (myComboBox1.getSelectedItem().equals("Normal")) {

            myLabel1.setFont(new Font("Fira Code", Font.PLAIN, 16));
        } else {

            myLabel1.setForeground(Color.RED);
        }
        myLabel1.setText(name);
    }//GEN-LAST:event_myButton3ActionPerformed

    private final int SIDEBAR_WIDTH = 200;
    private boolean isExpanded = true;
    private javax.swing.Timer slideTimer;

    private void toggleSidebar() {

        if (slideTimer != null && slideTimer.isRunning()) {
            return;
        }

        slideTimer = new javax.swing.Timer(10, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int currentWidth = jPanel3.getPreferredSize().width;
                int step = 10;
                int minWidth = sliderBtn.getWidth();
                if (isExpanded) {
                     sliderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ui/images/Slider_3.png")));
                        
                    if (currentWidth > minWidth) {
//                        
                            currentWidth = Math.max(minWidth, currentWidth-step);
                        jPanel3.setPreferredSize(new java.awt.Dimension(currentWidth, jPanel3.getHeight()));
                        if (jPanel3.getParent() != null) {
                        jPanel3.getParent().revalidate();
                    }
                        jPanel3.repaint();

                    } if(currentWidth<=minWidth) {
                       slideTimer.stop();
                        
                        isExpanded = false;
                    }
                } else {
//                    
                    sliderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ui/images/Slider_2.png")));
                      
                    if (currentWidth < SIDEBAR_WIDTH) {
                        currentWidth = Math.min(SIDEBAR_WIDTH, currentWidth+step);

                        jPanel3.setPreferredSize(new java.awt.Dimension(currentWidth, jPanel3.getHeight()));
                        if (jPanel3.getParent() != null) {
                        jPanel3.getParent().revalidate();
                    }
                        jPanel3.repaint();

                    } else {
                        slideTimer.stop();
                        isExpanded = true;
                    }

                }
            }
        });
        slideTimer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UiTest().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.mycompany.components.MyButton myButton1;
    private com.mycompany.components.MyButton myButton2;
    private com.mycompany.components.MyButton myButton3;
    private com.mycompany.components.MyButton myButton4;
    private com.mycompany.components.MyButton myButton5;
    private com.mycompany.components.MyButton myButton6;
    private com.mycompany.components.MyButton myButton7;
    private com.mycompany.components.MyComboBox myComboBox1;
    private com.mycompany.components.MyLabel myLabel1;
    private com.mycompany.components.MyTextField myTextField2;
    private com.mycompany.components.MyButton sliderBtn;
    // End of variables declaration//GEN-END:variables
}
